name: Rust

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        override: true
    - name: Install required target
      run: rustup target add aarch64-apple-darwin
    - name: Build project
      run: |
        export CFLAGS="-D__ARM_ARCH__"
        export CC=clang
        export RUST_BACKTRACE=1
        cargo build --verbose --release --target=aarch64-apple-darwin
    - name: Upload a Build Artifact (MacOS M1)
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Build MacOS
        path: ./target/aarch64-apple-darwin/release/proxyl
        retention-days: 1

